### ISSUE TITLE
Dates missing

### ISSUE THREAD

**Issue by chittyren** [azu/inkdrop-display-date-format#1]
Hello,

For some reason, the dates are missing after installing the plugin and reloading Inkdrop.  Below is a screengrab and software versions.
![image](https://user-images.githubusercontent.com/1612518/97090982-5ebd2100-1606-11eb-8dcf-f1a49f1f275f.png)

**Software Versions:**
Windows 10.0.19041
Inkdrop 5.1.1

Please let me know if you need any further information!  I would greatly appreciate any insights you might have!

Thank you in advance!

**Comment by azu** [comment]
https://blog.inkdrop.info/introducing-inkdrop-v5-5dee5873f953
Inkdrop5 move dates to "NOTE INFORMATION"(Editor Drawer).

<img width="280" alt="image" src="https://user-images.githubusercontent.com/19714/97169956-47c92b00-17ce-11eb-8b89-a6d9b2cd7af8.png">


Also, Inkdrop5 date format looks liks "YYYY-MM-DD ~" format.
So, This plugin is deprecated and I will archieve it
